name: Update READMEs and Push Changes

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-and-update-readmes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Fetch READMEs
      run: node ./scripts/fetch-readmes.js
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_ORG_NAME: ${{ secrets.ORG_NAME }}
        OUTPUT_DIR: 'content/posts'

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://${{ secrets.TOKEN }}@github.com/PeoplePlusAI/website-integration.git

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Automated README updates" -a || echo "No changes to commit"
        git push

